swagger: "2.0"
info:
  description: "API for my RSS backend"
  version: "1.0.0"
  title: "RSSReader"
  contact:
    email: "robbe@robbevanherck.be"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "rss.robbevanherck.be"
basePath: "/"
tags:
- name: "feed"
  description: "Everything related to RSS feeds"
- name: "post"
  description: "Everything related to specific posts"
schemes:
- "https"
paths:
  /feeds:
    get:
      tags:
      - feed
      summary: "Get all feeds"
      responses:
        "200":
          description: "All feeds"
          schema:
            $ref: "#/definitions/FeedList"
    post:
      tags:
      - "feed"
      summary: "Add a new feed to the list"
      operationId: "addFeed"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Feed to be added"
        required: true
        schema:
          $ref: "#/definitions/FeedNew"
      responses:
        200:
          description: "The newly created feed"
          schema:
            $ref: "#/definitions/Feed"
  /feeds/{feedId}:
    parameters:
      - name: "feedId"
        in: path
        required: true
        description: "The id of the feed"
        type: "integer"
    get:
      tags:
      - feed
      summary: "Get metadata about this feed"
      responses:
        200:
          description: "The requested feed"
          schema:
            $ref: '#/definitions/FeedDetail'
    delete:
      tags:
      - feed
      summary: "Remove the feed from the list"
      responses:
        204:
          description: "The feed was deleted succesfully"
    patch:
      tags:
      - feed
      summary: "Update the feed"
      responses:
        200:
          description: "The updated feed"
          schema:
            $ref: '#/definitions/Feed'
  /feeds/{feedId}/posts:
    parameters:
      - name: "feedId"
        in: path
        required: true
        description: "The id of the feed"
        type: "integer"
    get:
      tags:
      - "post"
      summary: "Get just the posts for this feed"
      description: "Get just the posts for this feed"
      responses:
        200:
          description: "All the posts"
          schema:
            $ref: '#/definitions/PostList'
  /feeds/{feedId}/posts/{postId}:
    parameters:
      - name: "feedId"
        in: path
        required: true
        description: "The id of the feed"
        type: "integer"
      - name: "postId"
        in: path
        required: true
        description: "The id of the post"
        type: "integer"
    get:
      tags:
      - "post"
      summary: "Get a specific post"
      responses:
        200:
          description: "The requested post"
          schema:
            $ref: '#/definitions/Post'
    delete:
      tags:
      - "post"
      summary: "Remove the post from the feed"
      responses:
        204:
          description: "The post was deleted succesfully"
    patch:
      tags:
      - "post"
      summary: "Update the post"
      responses:
        200:
          description: "The updated post"
          schema:
            $ref: '#/definitions/Post'
    
    
definitions:
  FeedNew:
    type: "object"
    required:
    - "name"
    - "url"
    properties:
      name:
        type: "string"
        example: "My awesome feed"
      url:
        type: "string"
        example: "https://example.com/feed.xml"
      priority:
        type: "integer"
        format: "int32"
        default: 1
        example: 1
      hidden:
        type: "boolean"
        default: false
  Feed:
    required:
    - "id"
    properties:
      id:
        type: "integer"
    allOf: 
    - $ref: '#/definitions/FeedNew'
  FeedList:
    type: "array"
    items:
      $ref: '#/definitions/Feed'
  FeedDetail:
    allOf:
    - $ref: '#/definitions/Feed'
    properties:
      posts:
        type: "array"
        items:
          $ref: '#/definitions/Post'
  Post:
    type: "object"
    required:
    - title
    - description
    - feed
    properties:
      id:
        type: "integer"
        example: 0
      title:
        type: "string"
        example: "A captivating title"
      description:
        type: "string"
        example: "This is a nice message"
      feed:
        type: "string"
        example: "https://rss.robbevanherck.be/feeds/0"
      link:
        type: "string"
        example: "https://example.com/captivating"
      read:
        type: "boolean"
        default: false
  PostList:
    type: "array"
    items:
      $ref: '#/definitions/Post'